=== servoronine/SmartHomeControl/Smart Home Control Service/ElectricityUsageLogger/Settings.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Definition">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="1" minOccurs="1" name="LocalSettings">
          <xs:complexType>
            <xs:attribute name="address" type="xs:string" use="required" />
            <xs:attribute name="dbConnection" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element maxOccurs="1" minOccurs="1" name="Remotes">
          <xs:complexType>
            <xs:sequence>            
              <xs:element maxOccurs="unbounded" name="Remote">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Commands">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="command" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="onProgramStart" type="xs:string" use="optional" />
                        <xs:attribute name="voicePrompt" type="xs:string" use="optional" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" use="required" />
                  <xs:attribute name="CommandLifeTime" type="xs:unsignedByte" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required" />
            <xs:attribute name="type" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element maxOccurs="1" minOccurs="1" name="Zones">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="Zone">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="Device">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="trigger">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element maxOccurs="unbounded" name="command" type="xs:string" />
                              </xs:sequence>
                              <xs:attribute name="senderType" type="xs:string" use="required" />
                              <xs:attribute name="sender" type="xs:string" use="required" />
                              <xs:attribute name="actionType" type="xs:string" use="required" />
                              <xs:attribute name="sequence" type="xs:unsignedByte" use="required" />
                              <xs:attribute name="action" type="xs:string" use="required" />
                              <xs:attribute name="value" type="xs:string" use="optional" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="type" type="xs:string" use="required" />
                        <xs:attribute name="name" type="xs:string" use="required" />
                        <xs:attribute name="number" type="xs:unsignedByte" use="required" />
                        <xs:attribute name="gateway" type="xs:string" use="required"></xs:attribute>
                        <xs:attribute name="location" type="xs:string" use="optional"></xs:attribute>
                        <xs:attribute name="port" type="xs:string" use="optional"></xs:attribute>
                        <xs:attribute name="loggingPollInterval" type="xs:unsignedShort" use="optional" />
                        <xs:attribute name="pinCode" type="xs:unsignedShort" use="optional" />
                        <xs:attribute name="params" type="xs:string" use="optional" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" use="required" />
                  <xs:attribute name="number" type="xs:unsignedByte" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== servoronine/SmartHomeControl/Smart Home Control Service/ElectricityUsageLogger/Settings.xml
<?xml version="1.0" encoding="utf-8" ?>
<Definition xmlns="http://smarthomecontrol.voronin.co.uk"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://smarthomecontrol.voronin.co.uk settings.xsd">

  <!-- You need to populate your global settings here-->
  <LocalSettings address="IP ADDRESS OF THE PC RUNNING THIS SERVICE" 
                 dbConnection="SQL SERVER CONNECTION STRING"
                 macAddress="MAC ADDRESS OF THE PC RUNNING THIS SERVICE, e.g. XX:XX:XX:XX:XX:XX"
                 homeCoordinates="YOUR HOME COORDINATES"/>

  <!--Gateways section is used to describe gateway devices. For example, LightwaveRF has a gateway which is then used to control lights and switches.
  It is not a device itself, i.e. its only function is to control other devices.
  This can also be a generic gateway. For example, any JSON message to online services will pass through the GenericJSONWebGateway-->
  <Gateways>
    <Gateway name="GenericIPGateway" type="SmartHomeControl.Devices.Generic.Gateways.GenericIPGateway"></Gateway>
    <Gateway name="LightwaveRFGateway" type="SmartHomeControl.Devices.LightwaveRF.LightwaveRFGateway">
      <Location>IP_ADDRESS</Location>
      <Port>9760</Port>
    </Gateway>
    <Gateway name="GenericXMLWebGateway" type="SmartHomeControl.Devices.Generic.Gateways.GenericXMLWebGateway"></Gateway>
    <Gateway name="GenericJSONWebGateway" type="SmartHomeControl.Devices.Generic.Gateways.GenericJSONWebGateway"></Gateway>
    <Gateway name="SonosGateway" type="SmartHomeControl.Devices.Sonos.SonosGateway"></Gateway>
  </Gateways>

  <!--Schedules section describes various schedules that can then be used to launch specific tasks-->
  <Schedules>
    <Schedule name="BackupOnSchedule" validDuringHoliday="true">
      <Daily>
        <Time>11:45</Time>
      </Daily>
    </Schedule>
    <Schedule name="BackupOffSchedule" validDuringHoliday="true">
      <Daily>
        <Time>14:00</Time>
      </Daily>
    </Schedule>
    <Schedule name="NightSchedule" validDuringHoliday="false">
      <Mon>
        <Time>01:00</Time>
      </Mon>
      <Tue>
        <Time>01:00</Time>
      </Tue>
      <Wed>
        <Time>01:00</Time>        
      </Wed>
      <Thu>
        <Time>01:00</Time>
      </Thu>
      <Fri>
        <Time>01:00</Time>
      </Fri>
      <Sat>
        <Time>02:00</Time>
      </Sat>
      <Sun>
        <Time>02:00</Time>        
      </Sun>
    </Schedule>
    <Schedule name="DaySchedule" validDuringHoliday="false">
      <Mon>
        <Time>07:30</Time>
      </Mon>
      <Tue>
        <Time>07:30</Time>
      </Tue>
      <Wed>
        <Time>07:30</Time>
      </Wed>
      <Thu>
        <Time>07:30</Time>
      </Thu>
      <Fri>
        <Time>07:30</Time>
      </Fri>
      <Sat>
        <Time>09:00</Time>
      </Sat>
      <Sun>
        <Time>09:00</Time>
      </Sun>
    </Schedule>
  </Schedules>

  <!--Remotes sections is used to describe your various remote controls. This can be a physical remote control, like your TV remote or virtual
  like the app on your phone. Here you also describe the various commands or buttons that the remote has as well as voice prompts to activate them-->
  <Remotes>
    <Remote name="LightwaveRFRemote" commandLifeTime="1">
      <Commands>
        <command>RegisterWithLightwaveRF</command>
        <command voicePrompt="sitting area light on|on sitting area light">SittingAreaLightOn</command>
        <command voicePrompt="sitting area light off|off sitting area light">SittingAreaLightOff</command>
        <command voicePrompt="dining area light on|on dining area light">DiningAreaLightOn</command>
        <command voicePrompt="dining area light off|off dining area light">DiningAreaLightOff</command>
        <command voicePrompt="corner light on|on corner light">CornerLightOn</command>
        <command voicePrompt="corner light off|off corner light">CornerLightOff</command>
        <command voicePrompt="sitting area light">SittingAreaLightDim</command>
        <command voicePrompt="dining area light">DiningAreaLightDim</command>
        <command voicePrompt="corner light">CornerLightDim</command>
        <command voicePrompt="hard drive socket on|on hard drive socket">HDDSocketOn</command>
        <command voicePrompt="hard drive socket off|off hard drive socket">HDDSocketOff</command>
        <command voicePrompt="sonos socket on|on sonos socket">SonosSocketOn</command>
        <command voicePrompt="sonos socket off|off sonos socket">SonosSocketOff</command>
        <command voicePrompt="kitchen sonos socket on|on kitchen sonos socket">KitchenSonosSocketOn</command>
        <command voicePrompt="kitchen sonos socket off|off kitchen sonos socket">KitchenSonosSocketOff</command>
        <command voicePrompt="kitchen cabinet lights on|on kitchen cabinet lights">KitchenCabinetLightsOn</command>
        <command voicePrompt="kitchen cabinet lights off|off kitchen cabinet lights">KitchenCabinetLightsOff</command>
        <command voicePrompt="all lounge lights on|all lights in the lounge on|on all lounge lights|on all lights in the lounge">AllLoungeLightsOn</command>
        <command voicePrompt="all lounge lights off|all lights in the lounge off|off all lounge lights|off all lights in the lounge">AllLoungeLightsOff</command>
        <command voicePrompt="kitchen light on|on kitchen light">KitchenLightOn</command>
        <command voicePrompt="kitchen light off|off kitchen light">KitchenLightOff</command>
        <command voicePrompt="front door light on|on front door light">FrontDoorLightOn</command>
        <command voicePrompt="front door light off|off front door light">FrontDoorLightOff</command>
        <command voicePrompt="hallway light on|on hallway light">HallwayLightOn</command>
        <command voicePrompt="hallway light off|off hallway light">HallwayLightOff</command>        
      </Commands>
    </Remote>
    <Remote name="HeatmiserRemote" commandLifeTime="1">
      <Commands>
        <command>SetDateTime</command>
        <command voicePrompt="toggle hot water" voiceResponse="OK. Hot water status changed.">ToggleHotWater</command>
        <command voicePrompt="switch on hot water|switch hot water on|turn on hot water|turn hot water on" voiceResponse="OK. Hot water is now on.">SwitchOnHotWater</command>
        <command voicePrompt="switch off hot water|switch hot water off|turn off hot water|turn hot water off" voiceResponse="OK. Hot water is now off.">SwitchOffHotWater</command>
        <command voicePrompt="make it warmer" voiceResponse="OK. I've increased the temperature by one degree.">IncreaseTemp</command>
        <command voicePrompt="make it colder" voiceResponse="OK. I've decreased the temperature by one degree.">DecreaseTemp</command>
      </Commands>
    </Remote>
    <Remote name="TimerRemote" commandLifeTime="1">
      <Commands>
        <command onProgramStart="true">LogEnergyConsumption</command>
        <command onProgramStart="true">LogHeatmiserState</command>
        <command onProgramStart="true">LogWebWeather</command>
        <command onProgramStart="true">StartCapturingJawboneData</command>
        <command onProgramStart="true">StartCapturingGreenIQData</command>
      </Commands>
    </Remote>
    <Remote name="OnkyoRemote" commandLifeTime="1">
      <Commands>
        <command>ReceiverOn</command>
        <command>ReceiverOff</command>
        <command voicePrompt="make the receiver louder">VolumeUpVoice</command>
        <command voicePrompt="make the receiver quieter">VolumeDownVoice</command>
        <command voicePrompt="play selected station">PlaySelectedStation</command>
        <command voicePrompt="stop the receiver">Stop</command>
        <command voicePrompt="press back on the receiver">Back</command>
        <command voicePrompt="mute the receiver">Mute</command>
        <command voicePrompt="unmute the receiver">UnMute</command>
        <command>SetVolume</command>
      </Commands>
    </Remote>
    <Remote name="MoodsRemote" commandLifeTime="1">
      <Commands>
        <command voicePrompt="relaxing" voiceResponse="OK. It's always good to take a moment to relax.">MusicWithDimmedLights</command>
        <command voicePrompt="watch TV" voiceResponse="OK. Enjoy your movie.">MovieWithDimmedLights</command>
        <command voicePrompt="done watching TV" voiceResponse="OK. I switched all devices off.">TVOff</command>
      </Commands>
    </Remote>
    <Remote name="HolidayManagerRemote" commandLifeTime="1">
      <Commands>
        <command>UpdateHolidays</command>
        <command voiceResponse="OK. I've added a holiday from {0} to {1}.">AddHoliday</command>
        <command voiceResponse="Noted. Nice to be back home, is it not?">CancelHoliday</command>
        <command voiceResponse="Ok. Your next planned holiday will be deleted.">DeleteNextPlannedHoliday</command>
        <command voiceResponse="OK. Your holiday starting on {0} will be deleted if found.">DeletePlannedHolidayStartingOn</command>
      </Commands>
    </Remote>
    <Remote name="PCRemote" commandLifeTime="1">
      <Commands>
        <command>TurnOnStudyPC</command>
        <command>TurnOffStudyPC</command>
        <command>TurnOnLoungePC</command>
        <command>TurnOffLoungePC</command>
      </Commands>
    </Remote>
    <Remote name="SonosRemote" commandLifeTime="1">
      <Commands>
        <Command voiceResponse="Enjoy your music">PlayFavoriteByNameKitchen</Command>
        <Command>StopKitchenPlayer</Command>
        <Command>MuteKitchen</Command>
        <Command>UnMuteKitchen</Command>
        <Command>SetVolumeKitchen</Command>
        <Command>VolumeUpVoice</Command>
        <Command>VolumeDownVoice</Command>
      </Commands>
    </Remote>
    <Remote name="LocationManagerRemote" commandLifeTime="1">
      <Commands>
        <Command>LogLocation</Command>
      </Commands>
    </Remote>
    <Remote name="GreenIQRemote" commandLifeTime="1">
      <Commands>
